create sequence hotelandes_sequence;

-- Creaacion de la tabla TIPOUSUARIO y especificacion de sus restricciones 
CREATE TABLE A_TIPOUSUARIO
   (ID NUMBER, 
	ROL VARCHAR2(255 BYTE) NOT NULL,
    DESCRIPCION VARCHAR2(255 BYTE) NOT NULL, 
	CONSTRAINT A_TIPOUSUARIO_PK PRIMARY KEY (ID));
	
SELECT * FROM A_TIPOUSUARIO;

ALTER TABLE A_TIPOUSUARIO
	ADD CONSTRAINT UN_TIPOUSU_ROL
	UNIQUE (ROL)
    ENABLE;

-- Creaacion de la tabla USUARIO y especificacion de sus restricciones
CREATE TABLE A_USUARIO
   (ID NUMBER, 
	NOMBRE VARCHAR2(255 BYTE) NOT NULL,
	ID_TIPOUSUARIO NUMBER NOT NULL, 
	CORREO VARCHAR2(255 BYTE) NOT NULL, 
	CONSTRAINT A_USUARIO_PK PRIMARY KEY (ID));
	
ALTER TABLE A_USUARIO
ADD CONSTRAINT fk_a_tipousuario
    FOREIGN KEY (id_tipousuario)
    REFERENCES a_tipousuario(id)
ENABLE;

-- Creacion de la tabla TIPOHABITACION y especificacion de sus restricciones.
CREATE TABLE A_TIPOHABITACION
   (ID NUMBER, 
	NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    CAPACIDAD NUMBER(2,0) NOT NULL,
	CONSTRAINT A_TIPOHABITACION_PK PRIMARY KEY (ID));
	
ALTER TABLE A_TIPOHABITACION
	ADD CONSTRAINT UN_TIPOHAB_NOMBRE
	UNIQUE (NOMBRE)
ENABLE;

-- Creaacion de la tabla HABITACION y especificacion de sus restricciones
CREATE TABLE A_HABITACION
   (ID NUMBER, 
	ID_TIPOHABITACION NUMBER, 
	CONSTRAINT A_HABITACION_PK PRIMARY KEY (ID));
	
ALTER TABLE A_HABITACION
ADD CONSTRAINT fk_a_tipohabitacion
    FOREIGN KEY (id_tipohabitacion)
    REFERENCES a_tipohabitacion(id)
ENABLE;

-- Creaacion de la tabla PLANCONSUMO y especificacion de sus restricciones
CREATE TABLE A_PLANCONSUMO
   (ID NUMBER, 
	NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    DESCRIPCION VARCHAR2(255 BYTE) NOT NULL,
    COSTO NUMBER NOT NULL,
	CONSTRAINT A_PLANCONSUMO_PK PRIMARY KEY (ID));
	
-- CreaaciÃ³n de la tabla RESERVAHABITACION y especificacion de sus restricciones
CREATE TABLE A_RESERVAHABITACION
   (ID NUMBER, 
	ID_CLIENTE NUMBER NOT NULL, 
    ID_HABITACION NUMBER NOT NULL,
    ID_PLAN NUMBER NOT NULL,
    FECHALLEGADA DATE NOT NULL,
    NOCHESRESERVADAS NUMBER(3,0) NOT NULL,
    CHECKIN CHAR(1) NOT NULL,
    CHECKOUT CHAR(1) NOT NULL,
	CONSTRAINT A_RESERVAHABITACION_PK PRIMARY KEY (ID));
	
ALTER TABLE A_RESERVAHABITACION
ADD(CONSTRAINT fk_a_cliente
    FOREIGN KEY (id_cliente)
    REFERENCES a_usuario(id)
    ENABLE,
    
    CONSTRAINT fk_a_habitacion
    FOREIGN KEY (id_habitacion)
    REFERENCES a_habitacion(id)
    ENABLE,
    
    CONSTRAINT fk_a_plan
    FOREIGN KEY (id_plan)
    REFERENCES a_planconsumo(id)
    ENABLE,
    
    CONSTRAINT CK_R_CHECKIN
    CHECK (checkin in ('Y','N'))
    ENABLE,
    
    CONSTRAINT CK_R_CHECKOUT
    CHECK (checkout in ('Y','N'))
    ENABLE);
    
CREATE TABLE A_SERVICIO
   (ID NUMBER, 
	NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    HORARIOINICIO TIMESTAMP NOT NULL,
    HORARIOFINAL TIMESTAMP NOT NULL,
	CONSTRAINT A_SERVICIO_PK PRIMARY KEY (ID));

CREATE TABLE A_RESERVASERVICIO
   (ID NUMBER, 
	ID_CLIENTE NUMBER NOT NULL,
    ID_SERVICIO NUMBER NOT NULL,
    HORARIOFINAL TIMESTAMP NOT NULL,
	CONSTRAINT A_RESERVASERVICIO_PK PRIMARY KEY (ID));    
    
ALTER TABLE A_RESERVASERVICIO
ADD(CONSTRAINT fk_a_rs_cliente
    FOREIGN KEY (id_cliente)
    REFERENCES a_usuario(id)
    ENABLE,
    
    CONSTRAINT fk_a_rs_servicio
    FOREIGN KEY (id_servicio)
    REFERENCES a_servicio(id)
    ENABLE);

CREATE TABLE A_PRODUCTO
   (ID NUMBER, 
	NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    COSTO NUMBER NOT NULL,
    ID_SERVICIO NUMBER NOT NULL,
	CONSTRAINT A_PRODUCTO_PK PRIMARY KEY (ID));     
    
ALTER TABLE A_PRODUCTO
ADD CONSTRAINT fk_a_p_servicio
    FOREIGN KEY (id_servicio)
    REFERENCES a_servicio(id)
ENABLE;

CREATE TABLE A_ITEM
   (ID NUMBER, 
	NOMBRE VARCHAR2(255 BYTE) NOT NULL,
	CONSTRAINT A_ITEM_PK PRIMARY KEY (ID));  

CREATE TABLE A_TIENEITEM
   (ID_TIPOHAB NUMBER, 
	ID_ITEM NUMBER,
	CONSTRAINT A_TIENEITEM_PK PRIMARY KEY (ID_TIPOHAB, ID_ITEM));     
    
ALTER TABLE A_TIENEITEM
ADD CONSTRAINT fk_a_tipohab
    FOREIGN KEY (id_tipohab)
    REFERENCES a_tipohabitacion(id)
ENABLE;

ALTER TABLE A_TIENEITEM
ADD CONSTRAINT fk_a_item
    FOREIGN KEY (id_item)
    REFERENCES a_item(id)
ENABLE;

COMMIT;
